[package]
name = "steam-audio-sys"
version = "0.3.0"
edition = "2021"
authors = ["Connor McCluskey <conmcclusk@gmail.com>"]
description = "Wrapper library for using steam audio in rust"
repository = "https://github.com/aceeri/steam-audio-rs.git"
readme = "README.md"
keywords = ["steam", "audio", "vr", "binaural", "gamedev", "hrtf", "phonon", "acoustics"]
categories = ["multimedia::audio", "games", "simulation"]
license-file = "LICENSE.md"
build = "build.rs"
resolver = "2"

[dependencies]

[build-dependencies]
bindgen = "0.59.2"

[dev-dependencies]
glfw = "0.43.0"
gl = "0.14.0"
lewton = "*"